/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type ClientVersion = { major: number; minor: number; patch: number };

export type ClientVersionArgs = ClientVersion;

export function getClientVersionEncoder(): FixedSizeEncoder<ClientVersionArgs> {
  return getStructEncoder([
    ['major', getU8Encoder()],
    ['minor', getU8Encoder()],
    ['patch', getU16Encoder()],
  ]);
}

export function getClientVersionDecoder(): FixedSizeDecoder<ClientVersion> {
  return getStructDecoder([
    ['major', getU8Decoder()],
    ['minor', getU8Decoder()],
    ['patch', getU16Decoder()],
  ]);
}

export function getClientVersionCodec(): FixedSizeCodec<
  ClientVersionArgs,
  ClientVersion
> {
  return combineCodec(getClientVersionEncoder(), getClientVersionDecoder());
}
