/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  getClientVersionDecoder,
  getClientVersionEncoder,
  type ClientVersion,
  type ClientVersionArgs,
} from '.';

export type ValidatorHistoryEntry = {
  activatedStakeLamports: bigint;
  epoch: number;
  mevCommission: number;
  epochCredits: number;
  commission: number;
  clientType: number;
  version: ClientVersion;
  ip: ReadonlyUint8Array;
  padding0: number;
  isSuperminority: number;
  rank: number;
  voteAccountLastUpdateSlot: bigint;
  mevEarned: number;
  padding1: ReadonlyUint8Array;
};

export type ValidatorHistoryEntryArgs = {
  activatedStakeLamports: number | bigint;
  epoch: number;
  mevCommission: number;
  epochCredits: number;
  commission: number;
  clientType: number;
  version: ClientVersionArgs;
  ip: ReadonlyUint8Array;
  padding0: number;
  isSuperminority: number;
  rank: number;
  voteAccountLastUpdateSlot: number | bigint;
  mevEarned: number;
  padding1: ReadonlyUint8Array;
};

export function getValidatorHistoryEntryEncoder(): FixedSizeEncoder<ValidatorHistoryEntryArgs> {
  return getStructEncoder([
    ['activatedStakeLamports', getU64Encoder()],
    ['epoch', getU16Encoder()],
    ['mevCommission', getU16Encoder()],
    ['epochCredits', getU32Encoder()],
    ['commission', getU8Encoder()],
    ['clientType', getU8Encoder()],
    ['version', getClientVersionEncoder()],
    ['ip', fixEncoderSize(getBytesEncoder(), 4)],
    ['padding0', getU8Encoder()],
    ['isSuperminority', getU8Encoder()],
    ['rank', getU32Encoder()],
    ['voteAccountLastUpdateSlot', getU64Encoder()],
    ['mevEarned', getU32Encoder()],
    ['padding1', fixEncoderSize(getBytesEncoder(), 84)],
  ]);
}

export function getValidatorHistoryEntryDecoder(): FixedSizeDecoder<ValidatorHistoryEntry> {
  return getStructDecoder([
    ['activatedStakeLamports', getU64Decoder()],
    ['epoch', getU16Decoder()],
    ['mevCommission', getU16Decoder()],
    ['epochCredits', getU32Decoder()],
    ['commission', getU8Decoder()],
    ['clientType', getU8Decoder()],
    ['version', getClientVersionDecoder()],
    ['ip', fixDecoderSize(getBytesDecoder(), 4)],
    ['padding0', getU8Decoder()],
    ['isSuperminority', getU8Decoder()],
    ['rank', getU32Decoder()],
    ['voteAccountLastUpdateSlot', getU64Decoder()],
    ['mevEarned', getU32Decoder()],
    ['padding1', fixDecoderSize(getBytesDecoder(), 84)],
  ]);
}

export function getValidatorHistoryEntryCodec(): FixedSizeCodec<
  ValidatorHistoryEntryArgs,
  ValidatorHistoryEntry
> {
  return combineCodec(
    getValidatorHistoryEntryEncoder(),
    getValidatorHistoryEntryDecoder()
  );
}
