/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { VALIDATOR_HISTORY_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const COPY_PRIORITY_FEE_DISTRIBUTION_DISCRIMINATOR = new Uint8Array([
  152, 174, 178, 77, 92, 83, 93, 33,
]);

export function getCopyPriorityFeeDistributionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    COPY_PRIORITY_FEE_DISTRIBUTION_DISCRIMINATOR
  );
}

export type CopyPriorityFeeDistributionInstruction<
  TProgram extends string = typeof VALIDATOR_HISTORY_PROGRAM_ADDRESS,
  TAccountValidatorHistoryAccount extends string | AccountMeta<string> = string,
  TAccountVoteAccount extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountDistributionAccount extends string | AccountMeta<string> = string,
  TAccountSigner extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountValidatorHistoryAccount extends string
        ? WritableAccount<TAccountValidatorHistoryAccount>
        : TAccountValidatorHistoryAccount,
      TAccountVoteAccount extends string
        ? ReadonlyAccount<TAccountVoteAccount>
        : TAccountVoteAccount,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountDistributionAccount extends string
        ? ReadonlyAccount<TAccountDistributionAccount>
        : TAccountDistributionAccount,
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      ...TRemainingAccounts,
    ]
  >;

export type CopyPriorityFeeDistributionInstructionData = {
  discriminator: ReadonlyUint8Array;
  epoch: bigint;
};

export type CopyPriorityFeeDistributionInstructionDataArgs = {
  epoch: number | bigint;
};

export function getCopyPriorityFeeDistributionInstructionDataEncoder(): FixedSizeEncoder<CopyPriorityFeeDistributionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['epoch', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: COPY_PRIORITY_FEE_DISTRIBUTION_DISCRIMINATOR,
    })
  );
}

export function getCopyPriorityFeeDistributionInstructionDataDecoder(): FixedSizeDecoder<CopyPriorityFeeDistributionInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['epoch', getU64Decoder()],
  ]);
}

export function getCopyPriorityFeeDistributionInstructionDataCodec(): FixedSizeCodec<
  CopyPriorityFeeDistributionInstructionDataArgs,
  CopyPriorityFeeDistributionInstructionData
> {
  return combineCodec(
    getCopyPriorityFeeDistributionInstructionDataEncoder(),
    getCopyPriorityFeeDistributionInstructionDataDecoder()
  );
}

export type CopyPriorityFeeDistributionInput<
  TAccountValidatorHistoryAccount extends string = string,
  TAccountVoteAccount extends string = string,
  TAccountConfig extends string = string,
  TAccountDistributionAccount extends string = string,
  TAccountSigner extends string = string,
> = {
  validatorHistoryAccount: Address<TAccountValidatorHistoryAccount>;
  /** Used to read validator commission. */
  voteAccount: Address<TAccountVoteAccount>;
  config: Address<TAccountConfig>;
  /** `owner = config.priority_fee_distribution_program.key()` here is sufficient. */
  distributionAccount: Address<TAccountDistributionAccount>;
  signer: TransactionSigner<TAccountSigner>;
  epoch: CopyPriorityFeeDistributionInstructionDataArgs['epoch'];
};

export function getCopyPriorityFeeDistributionInstruction<
  TAccountValidatorHistoryAccount extends string,
  TAccountVoteAccount extends string,
  TAccountConfig extends string,
  TAccountDistributionAccount extends string,
  TAccountSigner extends string,
  TProgramAddress extends Address = typeof VALIDATOR_HISTORY_PROGRAM_ADDRESS,
>(
  input: CopyPriorityFeeDistributionInput<
    TAccountValidatorHistoryAccount,
    TAccountVoteAccount,
    TAccountConfig,
    TAccountDistributionAccount,
    TAccountSigner
  >,
  config?: { programAddress?: TProgramAddress }
): CopyPriorityFeeDistributionInstruction<
  TProgramAddress,
  TAccountValidatorHistoryAccount,
  TAccountVoteAccount,
  TAccountConfig,
  TAccountDistributionAccount,
  TAccountSigner
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VALIDATOR_HISTORY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    validatorHistoryAccount: {
      value: input.validatorHistoryAccount ?? null,
      isWritable: true,
    },
    voteAccount: { value: input.voteAccount ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    distributionAccount: {
      value: input.distributionAccount ?? null,
      isWritable: false,
    },
    signer: { value: input.signer ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.validatorHistoryAccount),
      getAccountMeta(accounts.voteAccount),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.distributionAccount),
      getAccountMeta(accounts.signer),
    ],
    programAddress,
    data: getCopyPriorityFeeDistributionInstructionDataEncoder().encode(
      args as CopyPriorityFeeDistributionInstructionDataArgs
    ),
  } as CopyPriorityFeeDistributionInstruction<
    TProgramAddress,
    TAccountValidatorHistoryAccount,
    TAccountVoteAccount,
    TAccountConfig,
    TAccountDistributionAccount,
    TAccountSigner
  >;

  return instruction;
}

export type ParsedCopyPriorityFeeDistributionInstruction<
  TProgram extends string = typeof VALIDATOR_HISTORY_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    validatorHistoryAccount: TAccountMetas[0];
    /** Used to read validator commission. */
    voteAccount: TAccountMetas[1];
    config: TAccountMetas[2];
    /** `owner = config.priority_fee_distribution_program.key()` here is sufficient. */
    distributionAccount: TAccountMetas[3];
    signer: TAccountMetas[4];
  };
  data: CopyPriorityFeeDistributionInstructionData;
};

export function parseCopyPriorityFeeDistributionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCopyPriorityFeeDistributionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      validatorHistoryAccount: getNextAccount(),
      voteAccount: getNextAccount(),
      config: getNextAccount(),
      distributionAccount: getNextAccount(),
      signer: getNextAccount(),
    },
    data: getCopyPriorityFeeDistributionInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
