/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { VALIDATOR_HISTORY_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const INITIALIZE_CLUSTER_HISTORY_ACCOUNT_DISCRIMINATOR = new Uint8Array([
  8, 204, 21, 27, 253, 9, 10, 78,
]);

export function getInitializeClusterHistoryAccountDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_CLUSTER_HISTORY_ACCOUNT_DISCRIMINATOR
  );
}

export type InitializeClusterHistoryAccountInstruction<
  TProgram extends string = typeof VALIDATOR_HISTORY_PROGRAM_ADDRESS,
  TAccountClusterHistoryAccount extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountSigner extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountClusterHistoryAccount extends string
        ? WritableAccount<TAccountClusterHistoryAccount>
        : TAccountClusterHistoryAccount,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeClusterHistoryAccountInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type InitializeClusterHistoryAccountInstructionDataArgs = {};

export function getInitializeClusterHistoryAccountInstructionDataEncoder(): FixedSizeEncoder<InitializeClusterHistoryAccountInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_CLUSTER_HISTORY_ACCOUNT_DISCRIMINATOR,
    })
  );
}

export function getInitializeClusterHistoryAccountInstructionDataDecoder(): FixedSizeDecoder<InitializeClusterHistoryAccountInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getInitializeClusterHistoryAccountInstructionDataCodec(): FixedSizeCodec<
  InitializeClusterHistoryAccountInstructionDataArgs,
  InitializeClusterHistoryAccountInstructionData
> {
  return combineCodec(
    getInitializeClusterHistoryAccountInstructionDataEncoder(),
    getInitializeClusterHistoryAccountInstructionDataDecoder()
  );
}

export type InitializeClusterHistoryAccountInput<
  TAccountClusterHistoryAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountSigner extends string = string,
> = {
  clusterHistoryAccount: Address<TAccountClusterHistoryAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  signer: TransactionSigner<TAccountSigner>;
};

export function getInitializeClusterHistoryAccountInstruction<
  TAccountClusterHistoryAccount extends string,
  TAccountSystemProgram extends string,
  TAccountSigner extends string,
  TProgramAddress extends Address = typeof VALIDATOR_HISTORY_PROGRAM_ADDRESS,
>(
  input: InitializeClusterHistoryAccountInput<
    TAccountClusterHistoryAccount,
    TAccountSystemProgram,
    TAccountSigner
  >,
  config?: { programAddress?: TProgramAddress }
): InitializeClusterHistoryAccountInstruction<
  TProgramAddress,
  TAccountClusterHistoryAccount,
  TAccountSystemProgram,
  TAccountSigner
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VALIDATOR_HISTORY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    clusterHistoryAccount: {
      value: input.clusterHistoryAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    signer: { value: input.signer ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.clusterHistoryAccount),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.signer),
    ],
    programAddress,
    data: getInitializeClusterHistoryAccountInstructionDataEncoder().encode({}),
  } as InitializeClusterHistoryAccountInstruction<
    TProgramAddress,
    TAccountClusterHistoryAccount,
    TAccountSystemProgram,
    TAccountSigner
  >;

  return instruction;
}

export type ParsedInitializeClusterHistoryAccountInstruction<
  TProgram extends string = typeof VALIDATOR_HISTORY_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    clusterHistoryAccount: TAccountMetas[0];
    systemProgram: TAccountMetas[1];
    signer: TAccountMetas[2];
  };
  data: InitializeClusterHistoryAccountInstructionData;
};

export function parseInitializeClusterHistoryAccountInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInitializeClusterHistoryAccountInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      clusterHistoryAccount: getNextAccount(),
      systemProgram: getNextAccount(),
      signer: getNextAccount(),
    },
    data: getInitializeClusterHistoryAccountInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
