/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { VALIDATOR_HISTORY_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const INITIALIZE_VALIDATOR_HISTORY_ACCOUNT_DISCRIMINATOR =
  new Uint8Array([61, 152, 10, 77, 196, 242, 89, 36]);

export function getInitializeValidatorHistoryAccountDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_VALIDATOR_HISTORY_ACCOUNT_DISCRIMINATOR
  );
}

export type InitializeValidatorHistoryAccountInstruction<
  TProgram extends string = typeof VALIDATOR_HISTORY_PROGRAM_ADDRESS,
  TAccountValidatorHistoryAccount extends string | AccountMeta<string> = string,
  TAccountVoteAccount extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountSigner extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountValidatorHistoryAccount extends string
        ? WritableAccount<TAccountValidatorHistoryAccount>
        : TAccountValidatorHistoryAccount,
      TAccountVoteAccount extends string
        ? ReadonlyAccount<TAccountVoteAccount>
        : TAccountVoteAccount,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeValidatorHistoryAccountInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type InitializeValidatorHistoryAccountInstructionDataArgs = {};

export function getInitializeValidatorHistoryAccountInstructionDataEncoder(): FixedSizeEncoder<InitializeValidatorHistoryAccountInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_VALIDATOR_HISTORY_ACCOUNT_DISCRIMINATOR,
    })
  );
}

export function getInitializeValidatorHistoryAccountInstructionDataDecoder(): FixedSizeDecoder<InitializeValidatorHistoryAccountInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getInitializeValidatorHistoryAccountInstructionDataCodec(): FixedSizeCodec<
  InitializeValidatorHistoryAccountInstructionDataArgs,
  InitializeValidatorHistoryAccountInstructionData
> {
  return combineCodec(
    getInitializeValidatorHistoryAccountInstructionDataEncoder(),
    getInitializeValidatorHistoryAccountInstructionDataDecoder()
  );
}

export type InitializeValidatorHistoryAccountInput<
  TAccountValidatorHistoryAccount extends string = string,
  TAccountVoteAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountSigner extends string = string,
> = {
  validatorHistoryAccount: Address<TAccountValidatorHistoryAccount>;
  voteAccount: Address<TAccountVoteAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  signer: TransactionSigner<TAccountSigner>;
};

export function getInitializeValidatorHistoryAccountInstruction<
  TAccountValidatorHistoryAccount extends string,
  TAccountVoteAccount extends string,
  TAccountSystemProgram extends string,
  TAccountSigner extends string,
  TProgramAddress extends Address = typeof VALIDATOR_HISTORY_PROGRAM_ADDRESS,
>(
  input: InitializeValidatorHistoryAccountInput<
    TAccountValidatorHistoryAccount,
    TAccountVoteAccount,
    TAccountSystemProgram,
    TAccountSigner
  >,
  config?: { programAddress?: TProgramAddress }
): InitializeValidatorHistoryAccountInstruction<
  TProgramAddress,
  TAccountValidatorHistoryAccount,
  TAccountVoteAccount,
  TAccountSystemProgram,
  TAccountSigner
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VALIDATOR_HISTORY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    validatorHistoryAccount: {
      value: input.validatorHistoryAccount ?? null,
      isWritable: true,
    },
    voteAccount: { value: input.voteAccount ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    signer: { value: input.signer ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.validatorHistoryAccount),
      getAccountMeta(accounts.voteAccount),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.signer),
    ],
    programAddress,
    data: getInitializeValidatorHistoryAccountInstructionDataEncoder().encode(
      {}
    ),
  } as InitializeValidatorHistoryAccountInstruction<
    TProgramAddress,
    TAccountValidatorHistoryAccount,
    TAccountVoteAccount,
    TAccountSystemProgram,
    TAccountSigner
  >;

  return instruction;
}

export type ParsedInitializeValidatorHistoryAccountInstruction<
  TProgram extends string = typeof VALIDATOR_HISTORY_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    validatorHistoryAccount: TAccountMetas[0];
    voteAccount: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
    signer: TAccountMetas[3];
  };
  data: InitializeValidatorHistoryAccountInstructionData;
};

export function parseInitializeValidatorHistoryAccountInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInitializeValidatorHistoryAccountInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      validatorHistoryAccount: getNextAccount(),
      voteAccount: getNextAccount(),
      systemProgram: getNextAccount(),
      signer: getNextAccount(),
    },
    data: getInitializeValidatorHistoryAccountInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
