/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { VALIDATOR_HISTORY_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SET_NEW_ORACLE_AUTHORITY_DISCRIMINATOR = new Uint8Array([
  70, 73, 21, 170, 82, 128, 144, 56,
]);

export function getSetNewOracleAuthorityDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_NEW_ORACLE_AUTHORITY_DISCRIMINATOR
  );
}

export type SetNewOracleAuthorityInstruction<
  TProgram extends string = typeof VALIDATOR_HISTORY_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountNewOracleAuthority extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountNewOracleAuthority extends string
        ? ReadonlyAccount<TAccountNewOracleAuthority>
        : TAccountNewOracleAuthority,
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      ...TRemainingAccounts,
    ]
  >;

export type SetNewOracleAuthorityInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type SetNewOracleAuthorityInstructionDataArgs = {};

export function getSetNewOracleAuthorityInstructionDataEncoder(): FixedSizeEncoder<SetNewOracleAuthorityInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: SET_NEW_ORACLE_AUTHORITY_DISCRIMINATOR,
    })
  );
}

export function getSetNewOracleAuthorityInstructionDataDecoder(): FixedSizeDecoder<SetNewOracleAuthorityInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getSetNewOracleAuthorityInstructionDataCodec(): FixedSizeCodec<
  SetNewOracleAuthorityInstructionDataArgs,
  SetNewOracleAuthorityInstructionData
> {
  return combineCodec(
    getSetNewOracleAuthorityInstructionDataEncoder(),
    getSetNewOracleAuthorityInstructionDataDecoder()
  );
}

export type SetNewOracleAuthorityInput<
  TAccountConfig extends string = string,
  TAccountNewOracleAuthority extends string = string,
  TAccountAdmin extends string = string,
> = {
  config: Address<TAccountConfig>;
  newOracleAuthority: Address<TAccountNewOracleAuthority>;
  admin: TransactionSigner<TAccountAdmin>;
};

export function getSetNewOracleAuthorityInstruction<
  TAccountConfig extends string,
  TAccountNewOracleAuthority extends string,
  TAccountAdmin extends string,
  TProgramAddress extends Address = typeof VALIDATOR_HISTORY_PROGRAM_ADDRESS,
>(
  input: SetNewOracleAuthorityInput<
    TAccountConfig,
    TAccountNewOracleAuthority,
    TAccountAdmin
  >,
  config?: { programAddress?: TProgramAddress }
): SetNewOracleAuthorityInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountNewOracleAuthority,
  TAccountAdmin
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VALIDATOR_HISTORY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    newOracleAuthority: {
      value: input.newOracleAuthority ?? null,
      isWritable: false,
    },
    admin: { value: input.admin ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.newOracleAuthority),
      getAccountMeta(accounts.admin),
    ],
    programAddress,
    data: getSetNewOracleAuthorityInstructionDataEncoder().encode({}),
  } as SetNewOracleAuthorityInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountNewOracleAuthority,
    TAccountAdmin
  >;

  return instruction;
}

export type ParsedSetNewOracleAuthorityInstruction<
  TProgram extends string = typeof VALIDATOR_HISTORY_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    newOracleAuthority: TAccountMetas[1];
    admin: TAccountMetas[2];
  };
  data: SetNewOracleAuthorityInstructionData;
};

export function parseSetNewOracleAuthorityInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedSetNewOracleAuthorityInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      newOracleAuthority: getNextAccount(),
      admin: getNextAccount(),
    },
    data: getSetNewOracleAuthorityInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
