/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { VALIDATOR_HISTORY_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SET_NEW_PRIORITY_FEE_DISTRIBUTION_PROGRAM_DISCRIMINATOR =
  new Uint8Array([219, 234, 129, 224, 128, 162, 61, 174]);

export function getSetNewPriorityFeeDistributionProgramDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_NEW_PRIORITY_FEE_DISTRIBUTION_PROGRAM_DISCRIMINATOR
  );
}

export type SetNewPriorityFeeDistributionProgramInstruction<
  TProgram extends string = typeof VALIDATOR_HISTORY_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountNewPriorityFeeDistributionProgram extends
    | string
    | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountNewPriorityFeeDistributionProgram extends string
        ? ReadonlyAccount<TAccountNewPriorityFeeDistributionProgram>
        : TAccountNewPriorityFeeDistributionProgram,
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      ...TRemainingAccounts,
    ]
  >;

export type SetNewPriorityFeeDistributionProgramInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type SetNewPriorityFeeDistributionProgramInstructionDataArgs = {};

export function getSetNewPriorityFeeDistributionProgramInstructionDataEncoder(): FixedSizeEncoder<SetNewPriorityFeeDistributionProgramInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: SET_NEW_PRIORITY_FEE_DISTRIBUTION_PROGRAM_DISCRIMINATOR,
    })
  );
}

export function getSetNewPriorityFeeDistributionProgramInstructionDataDecoder(): FixedSizeDecoder<SetNewPriorityFeeDistributionProgramInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getSetNewPriorityFeeDistributionProgramInstructionDataCodec(): FixedSizeCodec<
  SetNewPriorityFeeDistributionProgramInstructionDataArgs,
  SetNewPriorityFeeDistributionProgramInstructionData
> {
  return combineCodec(
    getSetNewPriorityFeeDistributionProgramInstructionDataEncoder(),
    getSetNewPriorityFeeDistributionProgramInstructionDataDecoder()
  );
}

export type SetNewPriorityFeeDistributionProgramInput<
  TAccountConfig extends string = string,
  TAccountNewPriorityFeeDistributionProgram extends string = string,
  TAccountAdmin extends string = string,
> = {
  config: Address<TAccountConfig>;
  newPriorityFeeDistributionProgram: Address<TAccountNewPriorityFeeDistributionProgram>;
  admin: TransactionSigner<TAccountAdmin>;
};

export function getSetNewPriorityFeeDistributionProgramInstruction<
  TAccountConfig extends string,
  TAccountNewPriorityFeeDistributionProgram extends string,
  TAccountAdmin extends string,
  TProgramAddress extends Address = typeof VALIDATOR_HISTORY_PROGRAM_ADDRESS,
>(
  input: SetNewPriorityFeeDistributionProgramInput<
    TAccountConfig,
    TAccountNewPriorityFeeDistributionProgram,
    TAccountAdmin
  >,
  config?: { programAddress?: TProgramAddress }
): SetNewPriorityFeeDistributionProgramInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountNewPriorityFeeDistributionProgram,
  TAccountAdmin
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VALIDATOR_HISTORY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    newPriorityFeeDistributionProgram: {
      value: input.newPriorityFeeDistributionProgram ?? null,
      isWritable: false,
    },
    admin: { value: input.admin ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.newPriorityFeeDistributionProgram),
      getAccountMeta(accounts.admin),
    ],
    programAddress,
    data: getSetNewPriorityFeeDistributionProgramInstructionDataEncoder().encode(
      {}
    ),
  } as SetNewPriorityFeeDistributionProgramInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountNewPriorityFeeDistributionProgram,
    TAccountAdmin
  >;

  return instruction;
}

export type ParsedSetNewPriorityFeeDistributionProgramInstruction<
  TProgram extends string = typeof VALIDATOR_HISTORY_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    newPriorityFeeDistributionProgram: TAccountMetas[1];
    admin: TAccountMetas[2];
  };
  data: SetNewPriorityFeeDistributionProgramInstructionData;
};

export function parseSetNewPriorityFeeDistributionProgramInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedSetNewPriorityFeeDistributionProgramInstruction<
  TProgram,
  TAccountMetas
> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      newPriorityFeeDistributionProgram: getNextAccount(),
      admin: getNextAccount(),
    },
    data: getSetNewPriorityFeeDistributionProgramInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
