/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { STEWARD_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const ADMIN_MARK_FOR_REMOVAL_DISCRIMINATOR = new Uint8Array([
  213, 225, 98, 245, 9, 15, 154, 63,
]);

export function getAdminMarkForRemovalDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ADMIN_MARK_FOR_REMOVAL_DISCRIMINATOR
  );
}

export type AdminMarkForRemovalInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountStateAccount extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountStateAccount extends string
        ? WritableAccount<TAccountStateAccount>
        : TAccountStateAccount,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type AdminMarkForRemovalInstructionData = {
  discriminator: ReadonlyUint8Array;
  validatorListIndex: bigint;
  markForRemoval: number;
  immediate: number;
};

export type AdminMarkForRemovalInstructionDataArgs = {
  validatorListIndex: number | bigint;
  markForRemoval: number;
  immediate: number;
};

export function getAdminMarkForRemovalInstructionDataEncoder(): FixedSizeEncoder<AdminMarkForRemovalInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['validatorListIndex', getU64Encoder()],
      ['markForRemoval', getU8Encoder()],
      ['immediate', getU8Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: ADMIN_MARK_FOR_REMOVAL_DISCRIMINATOR,
    })
  );
}

export function getAdminMarkForRemovalInstructionDataDecoder(): FixedSizeDecoder<AdminMarkForRemovalInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['validatorListIndex', getU64Decoder()],
    ['markForRemoval', getU8Decoder()],
    ['immediate', getU8Decoder()],
  ]);
}

export function getAdminMarkForRemovalInstructionDataCodec(): FixedSizeCodec<
  AdminMarkForRemovalInstructionDataArgs,
  AdminMarkForRemovalInstructionData
> {
  return combineCodec(
    getAdminMarkForRemovalInstructionDataEncoder(),
    getAdminMarkForRemovalInstructionDataDecoder()
  );
}

export type AdminMarkForRemovalInput<
  TAccountConfig extends string = string,
  TAccountStateAccount extends string = string,
  TAccountAuthority extends string = string,
> = {
  config: Address<TAccountConfig>;
  stateAccount: Address<TAccountStateAccount>;
  authority: TransactionSigner<TAccountAuthority>;
  validatorListIndex: AdminMarkForRemovalInstructionDataArgs['validatorListIndex'];
  markForRemoval: AdminMarkForRemovalInstructionDataArgs['markForRemoval'];
  immediate: AdminMarkForRemovalInstructionDataArgs['immediate'];
};

export function getAdminMarkForRemovalInstruction<
  TAccountConfig extends string,
  TAccountStateAccount extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof STEWARD_PROGRAM_ADDRESS,
>(
  input: AdminMarkForRemovalInput<
    TAccountConfig,
    TAccountStateAccount,
    TAccountAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): AdminMarkForRemovalInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountStateAccount,
  TAccountAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? STEWARD_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    stateAccount: { value: input.stateAccount ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.stateAccount),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getAdminMarkForRemovalInstructionDataEncoder().encode(
      args as AdminMarkForRemovalInstructionDataArgs
    ),
  } as AdminMarkForRemovalInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountStateAccount,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedAdminMarkForRemovalInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    stateAccount: TAccountMetas[1];
    authority: TAccountMetas[2];
  };
  data: AdminMarkForRemovalInstructionData;
};

export function parseAdminMarkForRemovalInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedAdminMarkForRemovalInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      stateAccount: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getAdminMarkForRemovalInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
