/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from '@solana/kit';
import { STEWARD_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const EPOCH_MAINTENANCE_DISCRIMINATOR = new Uint8Array([
  208, 225, 211, 82, 219, 242, 58, 200,
]);

export function getEpochMaintenanceDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    EPOCH_MAINTENANCE_DISCRIMINATOR
  );
}

export type EpochMaintenanceInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountStateAccount extends string | AccountMeta<string> = string,
  TAccountValidatorList extends string | AccountMeta<string> = string,
  TAccountStakePool extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountStateAccount extends string
        ? WritableAccount<TAccountStateAccount>
        : TAccountStateAccount,
      TAccountValidatorList extends string
        ? ReadonlyAccount<TAccountValidatorList>
        : TAccountValidatorList,
      TAccountStakePool extends string
        ? ReadonlyAccount<TAccountStakePool>
        : TAccountStakePool,
      ...TRemainingAccounts,
    ]
  >;

export type EpochMaintenanceInstructionData = {
  discriminator: ReadonlyUint8Array;
  validatorIndexToRemove: Option<bigint>;
};

export type EpochMaintenanceInstructionDataArgs = {
  validatorIndexToRemove: OptionOrNullable<number | bigint>;
};

export function getEpochMaintenanceInstructionDataEncoder(): Encoder<EpochMaintenanceInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['validatorIndexToRemove', getOptionEncoder(getU64Encoder())],
    ]),
    (value) => ({ ...value, discriminator: EPOCH_MAINTENANCE_DISCRIMINATOR })
  );
}

export function getEpochMaintenanceInstructionDataDecoder(): Decoder<EpochMaintenanceInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['validatorIndexToRemove', getOptionDecoder(getU64Decoder())],
  ]);
}

export function getEpochMaintenanceInstructionDataCodec(): Codec<
  EpochMaintenanceInstructionDataArgs,
  EpochMaintenanceInstructionData
> {
  return combineCodec(
    getEpochMaintenanceInstructionDataEncoder(),
    getEpochMaintenanceInstructionDataDecoder()
  );
}

export type EpochMaintenanceInput<
  TAccountConfig extends string = string,
  TAccountStateAccount extends string = string,
  TAccountValidatorList extends string = string,
  TAccountStakePool extends string = string,
> = {
  config: Address<TAccountConfig>;
  stateAccount: Address<TAccountStateAccount>;
  validatorList: Address<TAccountValidatorList>;
  stakePool: Address<TAccountStakePool>;
  validatorIndexToRemove: EpochMaintenanceInstructionDataArgs['validatorIndexToRemove'];
};

export function getEpochMaintenanceInstruction<
  TAccountConfig extends string,
  TAccountStateAccount extends string,
  TAccountValidatorList extends string,
  TAccountStakePool extends string,
  TProgramAddress extends Address = typeof STEWARD_PROGRAM_ADDRESS,
>(
  input: EpochMaintenanceInput<
    TAccountConfig,
    TAccountStateAccount,
    TAccountValidatorList,
    TAccountStakePool
  >,
  config?: { programAddress?: TProgramAddress }
): EpochMaintenanceInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountStateAccount,
  TAccountValidatorList,
  TAccountStakePool
> {
  // Program address.
  const programAddress = config?.programAddress ?? STEWARD_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    stateAccount: { value: input.stateAccount ?? null, isWritable: true },
    validatorList: { value: input.validatorList ?? null, isWritable: false },
    stakePool: { value: input.stakePool ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.stateAccount),
      getAccountMeta(accounts.validatorList),
      getAccountMeta(accounts.stakePool),
    ],
    programAddress,
    data: getEpochMaintenanceInstructionDataEncoder().encode(
      args as EpochMaintenanceInstructionDataArgs
    ),
  } as EpochMaintenanceInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountStateAccount,
    TAccountValidatorList,
    TAccountStakePool
  >;

  return instruction;
}

export type ParsedEpochMaintenanceInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    stateAccount: TAccountMetas[1];
    validatorList: TAccountMetas[2];
    stakePool: TAccountMetas[3];
  };
  data: EpochMaintenanceInstructionData;
};

export function parseEpochMaintenanceInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedEpochMaintenanceInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      stateAccount: getNextAccount(),
      validatorList: getNextAccount(),
      stakePool: getNextAccount(),
    },
    data: getEpochMaintenanceInstructionDataDecoder().decode(instruction.data),
  };
}
