/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { STEWARD_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const INCREASE_ADDITIONAL_VALIDATOR_STAKE_DISCRIMINATOR = new Uint8Array(
  [93, 136, 94, 230, 32, 54, 167, 242]
);

export function getIncreaseAdditionalValidatorStakeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INCREASE_ADDITIONAL_VALIDATOR_STAKE_DISCRIMINATOR
  );
}

export type IncreaseAdditionalValidatorStakeInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountStateAccount extends string | AccountMeta<string> = string,
  TAccountValidatorHistory extends string | AccountMeta<string> = string,
  TAccountStakePoolProgram extends string | AccountMeta<string> = string,
  TAccountStakePool extends string | AccountMeta<string> = string,
  TAccountWithdrawAuthority extends string | AccountMeta<string> = string,
  TAccountValidatorList extends string | AccountMeta<string> = string,
  TAccountReserveStake extends string | AccountMeta<string> = string,
  TAccountEphemeralStakeAccount extends string | AccountMeta<string> = string,
  TAccountTransientStakeAccount extends string | AccountMeta<string> = string,
  TAccountStakeAccount extends string | AccountMeta<string> = string,
  TAccountVoteAccount extends string | AccountMeta<string> = string,
  TAccountClock extends string | AccountMeta<string> = string,
  TAccountStakeHistory extends string | AccountMeta<string> = string,
  TAccountStakeConfig extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountStakeProgram extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountStateAccount extends string
        ? WritableAccount<TAccountStateAccount>
        : TAccountStateAccount,
      TAccountValidatorHistory extends string
        ? WritableAccount<TAccountValidatorHistory>
        : TAccountValidatorHistory,
      TAccountStakePoolProgram extends string
        ? ReadonlyAccount<TAccountStakePoolProgram>
        : TAccountStakePoolProgram,
      TAccountStakePool extends string
        ? ReadonlyAccount<TAccountStakePool>
        : TAccountStakePool,
      TAccountWithdrawAuthority extends string
        ? ReadonlyAccount<TAccountWithdrawAuthority>
        : TAccountWithdrawAuthority,
      TAccountValidatorList extends string
        ? WritableAccount<TAccountValidatorList>
        : TAccountValidatorList,
      TAccountReserveStake extends string
        ? WritableAccount<TAccountReserveStake>
        : TAccountReserveStake,
      TAccountEphemeralStakeAccount extends string
        ? WritableAccount<TAccountEphemeralStakeAccount>
        : TAccountEphemeralStakeAccount,
      TAccountTransientStakeAccount extends string
        ? WritableAccount<TAccountTransientStakeAccount>
        : TAccountTransientStakeAccount,
      TAccountStakeAccount extends string
        ? ReadonlyAccount<TAccountStakeAccount>
        : TAccountStakeAccount,
      TAccountVoteAccount extends string
        ? ReadonlyAccount<TAccountVoteAccount>
        : TAccountVoteAccount,
      TAccountClock extends string
        ? ReadonlyAccount<TAccountClock>
        : TAccountClock,
      TAccountStakeHistory extends string
        ? ReadonlyAccount<TAccountStakeHistory>
        : TAccountStakeHistory,
      TAccountStakeConfig extends string
        ? ReadonlyAccount<TAccountStakeConfig>
        : TAccountStakeConfig,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountStakeProgram extends string
        ? ReadonlyAccount<TAccountStakeProgram>
        : TAccountStakeProgram,
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      ...TRemainingAccounts,
    ]
  >;

export type IncreaseAdditionalValidatorStakeInstructionData = {
  discriminator: ReadonlyUint8Array;
  lamports: bigint;
  transientSeed: bigint;
  ephemeralSeed: bigint;
};

export type IncreaseAdditionalValidatorStakeInstructionDataArgs = {
  lamports: number | bigint;
  transientSeed: number | bigint;
  ephemeralSeed: number | bigint;
};

export function getIncreaseAdditionalValidatorStakeInstructionDataEncoder(): FixedSizeEncoder<IncreaseAdditionalValidatorStakeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['lamports', getU64Encoder()],
      ['transientSeed', getU64Encoder()],
      ['ephemeralSeed', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: INCREASE_ADDITIONAL_VALIDATOR_STAKE_DISCRIMINATOR,
    })
  );
}

export function getIncreaseAdditionalValidatorStakeInstructionDataDecoder(): FixedSizeDecoder<IncreaseAdditionalValidatorStakeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['lamports', getU64Decoder()],
    ['transientSeed', getU64Decoder()],
    ['ephemeralSeed', getU64Decoder()],
  ]);
}

export function getIncreaseAdditionalValidatorStakeInstructionDataCodec(): FixedSizeCodec<
  IncreaseAdditionalValidatorStakeInstructionDataArgs,
  IncreaseAdditionalValidatorStakeInstructionData
> {
  return combineCodec(
    getIncreaseAdditionalValidatorStakeInstructionDataEncoder(),
    getIncreaseAdditionalValidatorStakeInstructionDataDecoder()
  );
}

export type IncreaseAdditionalValidatorStakeInput<
  TAccountConfig extends string = string,
  TAccountStateAccount extends string = string,
  TAccountValidatorHistory extends string = string,
  TAccountStakePoolProgram extends string = string,
  TAccountStakePool extends string = string,
  TAccountWithdrawAuthority extends string = string,
  TAccountValidatorList extends string = string,
  TAccountReserveStake extends string = string,
  TAccountEphemeralStakeAccount extends string = string,
  TAccountTransientStakeAccount extends string = string,
  TAccountStakeAccount extends string = string,
  TAccountVoteAccount extends string = string,
  TAccountClock extends string = string,
  TAccountStakeHistory extends string = string,
  TAccountStakeConfig extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountStakeProgram extends string = string,
  TAccountAdmin extends string = string,
> = {
  config: Address<TAccountConfig>;
  stateAccount: Address<TAccountStateAccount>;
  validatorHistory: Address<TAccountValidatorHistory>;
  stakePoolProgram: Address<TAccountStakePoolProgram>;
  stakePool: Address<TAccountStakePool>;
  withdrawAuthority: Address<TAccountWithdrawAuthority>;
  validatorList: Address<TAccountValidatorList>;
  reserveStake: Address<TAccountReserveStake>;
  ephemeralStakeAccount: Address<TAccountEphemeralStakeAccount>;
  transientStakeAccount: Address<TAccountTransientStakeAccount>;
  stakeAccount: Address<TAccountStakeAccount>;
  voteAccount: Address<TAccountVoteAccount>;
  clock: Address<TAccountClock>;
  stakeHistory: Address<TAccountStakeHistory>;
  stakeConfig: Address<TAccountStakeConfig>;
  systemProgram?: Address<TAccountSystemProgram>;
  stakeProgram: Address<TAccountStakeProgram>;
  admin: TransactionSigner<TAccountAdmin>;
  lamports: IncreaseAdditionalValidatorStakeInstructionDataArgs['lamports'];
  transientSeed: IncreaseAdditionalValidatorStakeInstructionDataArgs['transientSeed'];
  ephemeralSeed: IncreaseAdditionalValidatorStakeInstructionDataArgs['ephemeralSeed'];
};

export function getIncreaseAdditionalValidatorStakeInstruction<
  TAccountConfig extends string,
  TAccountStateAccount extends string,
  TAccountValidatorHistory extends string,
  TAccountStakePoolProgram extends string,
  TAccountStakePool extends string,
  TAccountWithdrawAuthority extends string,
  TAccountValidatorList extends string,
  TAccountReserveStake extends string,
  TAccountEphemeralStakeAccount extends string,
  TAccountTransientStakeAccount extends string,
  TAccountStakeAccount extends string,
  TAccountVoteAccount extends string,
  TAccountClock extends string,
  TAccountStakeHistory extends string,
  TAccountStakeConfig extends string,
  TAccountSystemProgram extends string,
  TAccountStakeProgram extends string,
  TAccountAdmin extends string,
  TProgramAddress extends Address = typeof STEWARD_PROGRAM_ADDRESS,
>(
  input: IncreaseAdditionalValidatorStakeInput<
    TAccountConfig,
    TAccountStateAccount,
    TAccountValidatorHistory,
    TAccountStakePoolProgram,
    TAccountStakePool,
    TAccountWithdrawAuthority,
    TAccountValidatorList,
    TAccountReserveStake,
    TAccountEphemeralStakeAccount,
    TAccountTransientStakeAccount,
    TAccountStakeAccount,
    TAccountVoteAccount,
    TAccountClock,
    TAccountStakeHistory,
    TAccountStakeConfig,
    TAccountSystemProgram,
    TAccountStakeProgram,
    TAccountAdmin
  >,
  config?: { programAddress?: TProgramAddress }
): IncreaseAdditionalValidatorStakeInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountStateAccount,
  TAccountValidatorHistory,
  TAccountStakePoolProgram,
  TAccountStakePool,
  TAccountWithdrawAuthority,
  TAccountValidatorList,
  TAccountReserveStake,
  TAccountEphemeralStakeAccount,
  TAccountTransientStakeAccount,
  TAccountStakeAccount,
  TAccountVoteAccount,
  TAccountClock,
  TAccountStakeHistory,
  TAccountStakeConfig,
  TAccountSystemProgram,
  TAccountStakeProgram,
  TAccountAdmin
> {
  // Program address.
  const programAddress = config?.programAddress ?? STEWARD_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    stateAccount: { value: input.stateAccount ?? null, isWritable: true },
    validatorHistory: {
      value: input.validatorHistory ?? null,
      isWritable: true,
    },
    stakePoolProgram: {
      value: input.stakePoolProgram ?? null,
      isWritable: false,
    },
    stakePool: { value: input.stakePool ?? null, isWritable: false },
    withdrawAuthority: {
      value: input.withdrawAuthority ?? null,
      isWritable: false,
    },
    validatorList: { value: input.validatorList ?? null, isWritable: true },
    reserveStake: { value: input.reserveStake ?? null, isWritable: true },
    ephemeralStakeAccount: {
      value: input.ephemeralStakeAccount ?? null,
      isWritable: true,
    },
    transientStakeAccount: {
      value: input.transientStakeAccount ?? null,
      isWritable: true,
    },
    stakeAccount: { value: input.stakeAccount ?? null, isWritable: false },
    voteAccount: { value: input.voteAccount ?? null, isWritable: false },
    clock: { value: input.clock ?? null, isWritable: false },
    stakeHistory: { value: input.stakeHistory ?? null, isWritable: false },
    stakeConfig: { value: input.stakeConfig ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    stakeProgram: { value: input.stakeProgram ?? null, isWritable: false },
    admin: { value: input.admin ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.stateAccount),
      getAccountMeta(accounts.validatorHistory),
      getAccountMeta(accounts.stakePoolProgram),
      getAccountMeta(accounts.stakePool),
      getAccountMeta(accounts.withdrawAuthority),
      getAccountMeta(accounts.validatorList),
      getAccountMeta(accounts.reserveStake),
      getAccountMeta(accounts.ephemeralStakeAccount),
      getAccountMeta(accounts.transientStakeAccount),
      getAccountMeta(accounts.stakeAccount),
      getAccountMeta(accounts.voteAccount),
      getAccountMeta(accounts.clock),
      getAccountMeta(accounts.stakeHistory),
      getAccountMeta(accounts.stakeConfig),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.stakeProgram),
      getAccountMeta(accounts.admin),
    ],
    programAddress,
    data: getIncreaseAdditionalValidatorStakeInstructionDataEncoder().encode(
      args as IncreaseAdditionalValidatorStakeInstructionDataArgs
    ),
  } as IncreaseAdditionalValidatorStakeInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountStateAccount,
    TAccountValidatorHistory,
    TAccountStakePoolProgram,
    TAccountStakePool,
    TAccountWithdrawAuthority,
    TAccountValidatorList,
    TAccountReserveStake,
    TAccountEphemeralStakeAccount,
    TAccountTransientStakeAccount,
    TAccountStakeAccount,
    TAccountVoteAccount,
    TAccountClock,
    TAccountStakeHistory,
    TAccountStakeConfig,
    TAccountSystemProgram,
    TAccountStakeProgram,
    TAccountAdmin
  >;

  return instruction;
}

export type ParsedIncreaseAdditionalValidatorStakeInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    stateAccount: TAccountMetas[1];
    validatorHistory: TAccountMetas[2];
    stakePoolProgram: TAccountMetas[3];
    stakePool: TAccountMetas[4];
    withdrawAuthority: TAccountMetas[5];
    validatorList: TAccountMetas[6];
    reserveStake: TAccountMetas[7];
    ephemeralStakeAccount: TAccountMetas[8];
    transientStakeAccount: TAccountMetas[9];
    stakeAccount: TAccountMetas[10];
    voteAccount: TAccountMetas[11];
    clock: TAccountMetas[12];
    stakeHistory: TAccountMetas[13];
    stakeConfig: TAccountMetas[14];
    systemProgram: TAccountMetas[15];
    stakeProgram: TAccountMetas[16];
    admin: TAccountMetas[17];
  };
  data: IncreaseAdditionalValidatorStakeInstructionData;
};

export function parseIncreaseAdditionalValidatorStakeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedIncreaseAdditionalValidatorStakeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 18) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      stateAccount: getNextAccount(),
      validatorHistory: getNextAccount(),
      stakePoolProgram: getNextAccount(),
      stakePool: getNextAccount(),
      withdrawAuthority: getNextAccount(),
      validatorList: getNextAccount(),
      reserveStake: getNextAccount(),
      ephemeralStakeAccount: getNextAccount(),
      transientStakeAccount: getNextAccount(),
      stakeAccount: getNextAccount(),
      voteAccount: getNextAccount(),
      clock: getNextAccount(),
      stakeHistory: getNextAccount(),
      stakeConfig: getNextAccount(),
      systemProgram: getNextAccount(),
      stakeProgram: getNextAccount(),
      admin: getNextAccount(),
    },
    data: getIncreaseAdditionalValidatorStakeInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
