/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from '@solana/kit';
import { STEWARD_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const INSTANT_REMOVE_VALIDATOR_DISCRIMINATOR = new Uint8Array([
  119, 127, 216, 135, 24, 63, 229, 242,
]);

export function getInstantRemoveValidatorDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INSTANT_REMOVE_VALIDATOR_DISCRIMINATOR
  );
}

export type InstantRemoveValidatorInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountStateAccount extends string | AccountMeta<string> = string,
  TAccountValidatorList extends string | AccountMeta<string> = string,
  TAccountStakePool extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountStateAccount extends string
        ? WritableAccount<TAccountStateAccount>
        : TAccountStateAccount,
      TAccountValidatorList extends string
        ? ReadonlyAccount<TAccountValidatorList>
        : TAccountValidatorList,
      TAccountStakePool extends string
        ? ReadonlyAccount<TAccountStakePool>
        : TAccountStakePool,
      ...TRemainingAccounts,
    ]
  >;

export type InstantRemoveValidatorInstructionData = {
  discriminator: ReadonlyUint8Array;
  validatorIndexToRemove: bigint;
};

export type InstantRemoveValidatorInstructionDataArgs = {
  validatorIndexToRemove: number | bigint;
};

export function getInstantRemoveValidatorInstructionDataEncoder(): FixedSizeEncoder<InstantRemoveValidatorInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['validatorIndexToRemove', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: INSTANT_REMOVE_VALIDATOR_DISCRIMINATOR,
    })
  );
}

export function getInstantRemoveValidatorInstructionDataDecoder(): FixedSizeDecoder<InstantRemoveValidatorInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['validatorIndexToRemove', getU64Decoder()],
  ]);
}

export function getInstantRemoveValidatorInstructionDataCodec(): FixedSizeCodec<
  InstantRemoveValidatorInstructionDataArgs,
  InstantRemoveValidatorInstructionData
> {
  return combineCodec(
    getInstantRemoveValidatorInstructionDataEncoder(),
    getInstantRemoveValidatorInstructionDataDecoder()
  );
}

export type InstantRemoveValidatorInput<
  TAccountConfig extends string = string,
  TAccountStateAccount extends string = string,
  TAccountValidatorList extends string = string,
  TAccountStakePool extends string = string,
> = {
  config: Address<TAccountConfig>;
  stateAccount: Address<TAccountStateAccount>;
  validatorList: Address<TAccountValidatorList>;
  stakePool: Address<TAccountStakePool>;
  validatorIndexToRemove: InstantRemoveValidatorInstructionDataArgs['validatorIndexToRemove'];
};

export function getInstantRemoveValidatorInstruction<
  TAccountConfig extends string,
  TAccountStateAccount extends string,
  TAccountValidatorList extends string,
  TAccountStakePool extends string,
  TProgramAddress extends Address = typeof STEWARD_PROGRAM_ADDRESS,
>(
  input: InstantRemoveValidatorInput<
    TAccountConfig,
    TAccountStateAccount,
    TAccountValidatorList,
    TAccountStakePool
  >,
  config?: { programAddress?: TProgramAddress }
): InstantRemoveValidatorInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountStateAccount,
  TAccountValidatorList,
  TAccountStakePool
> {
  // Program address.
  const programAddress = config?.programAddress ?? STEWARD_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    stateAccount: { value: input.stateAccount ?? null, isWritable: true },
    validatorList: { value: input.validatorList ?? null, isWritable: false },
    stakePool: { value: input.stakePool ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.stateAccount),
      getAccountMeta(accounts.validatorList),
      getAccountMeta(accounts.stakePool),
    ],
    programAddress,
    data: getInstantRemoveValidatorInstructionDataEncoder().encode(
      args as InstantRemoveValidatorInstructionDataArgs
    ),
  } as InstantRemoveValidatorInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountStateAccount,
    TAccountValidatorList,
    TAccountStakePool
  >;

  return instruction;
}

export type ParsedInstantRemoveValidatorInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    stateAccount: TAccountMetas[1];
    validatorList: TAccountMetas[2];
    stakePool: TAccountMetas[3];
  };
  data: InstantRemoveValidatorInstructionData;
};

export function parseInstantRemoveValidatorInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInstantRemoveValidatorInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      stateAccount: getNextAccount(),
      validatorList: getNextAccount(),
      stakePool: getNextAccount(),
    },
    data: getInstantRemoveValidatorInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
