/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { STEWARD_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const REALLOC_STATE_DISCRIMINATOR = new Uint8Array([
  67, 181, 233, 214, 215, 148, 245, 126,
]);

export function getReallocStateDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REALLOC_STATE_DISCRIMINATOR
  );
}

export type ReallocStateInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountStateAccount extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountValidatorList extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountSigner extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountStateAccount extends string
        ? WritableAccount<TAccountStateAccount>
        : TAccountStateAccount,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountValidatorList extends string
        ? ReadonlyAccount<TAccountValidatorList>
        : TAccountValidatorList,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      ...TRemainingAccounts,
    ]
  >;

export type ReallocStateInstructionData = { discriminator: ReadonlyUint8Array };

export type ReallocStateInstructionDataArgs = {};

export function getReallocStateInstructionDataEncoder(): FixedSizeEncoder<ReallocStateInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: REALLOC_STATE_DISCRIMINATOR })
  );
}

export function getReallocStateInstructionDataDecoder(): FixedSizeDecoder<ReallocStateInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getReallocStateInstructionDataCodec(): FixedSizeCodec<
  ReallocStateInstructionDataArgs,
  ReallocStateInstructionData
> {
  return combineCodec(
    getReallocStateInstructionDataEncoder(),
    getReallocStateInstructionDataDecoder()
  );
}

export type ReallocStateInput<
  TAccountStateAccount extends string = string,
  TAccountConfig extends string = string,
  TAccountValidatorList extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountSigner extends string = string,
> = {
  stateAccount: Address<TAccountStateAccount>;
  config: Address<TAccountConfig>;
  validatorList: Address<TAccountValidatorList>;
  systemProgram?: Address<TAccountSystemProgram>;
  signer: TransactionSigner<TAccountSigner>;
};

export function getReallocStateInstruction<
  TAccountStateAccount extends string,
  TAccountConfig extends string,
  TAccountValidatorList extends string,
  TAccountSystemProgram extends string,
  TAccountSigner extends string,
  TProgramAddress extends Address = typeof STEWARD_PROGRAM_ADDRESS,
>(
  input: ReallocStateInput<
    TAccountStateAccount,
    TAccountConfig,
    TAccountValidatorList,
    TAccountSystemProgram,
    TAccountSigner
  >,
  config?: { programAddress?: TProgramAddress }
): ReallocStateInstruction<
  TProgramAddress,
  TAccountStateAccount,
  TAccountConfig,
  TAccountValidatorList,
  TAccountSystemProgram,
  TAccountSigner
> {
  // Program address.
  const programAddress = config?.programAddress ?? STEWARD_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    stateAccount: { value: input.stateAccount ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    validatorList: { value: input.validatorList ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    signer: { value: input.signer ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.stateAccount),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.validatorList),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.signer),
    ],
    programAddress,
    data: getReallocStateInstructionDataEncoder().encode({}),
  } as ReallocStateInstruction<
    TProgramAddress,
    TAccountStateAccount,
    TAccountConfig,
    TAccountValidatorList,
    TAccountSystemProgram,
    TAccountSigner
  >;

  return instruction;
}

export type ParsedReallocStateInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    stateAccount: TAccountMetas[0];
    config: TAccountMetas[1];
    validatorList: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
    signer: TAccountMetas[4];
  };
  data: ReallocStateInstructionData;
};

export function parseReallocStateInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedReallocStateInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      stateAccount: getNextAccount(),
      config: getNextAccount(),
      validatorList: getNextAccount(),
      systemProgram: getNextAccount(),
      signer: getNextAccount(),
    },
    data: getReallocStateInstructionDataDecoder().decode(instruction.data),
  };
}
