/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { STEWARD_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const RESET_STEWARD_STATE_DISCRIMINATOR = new Uint8Array([
  84, 248, 158, 46, 200, 205, 234, 86,
]);

export function getResetStewardStateDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    RESET_STEWARD_STATE_DISCRIMINATOR
  );
}

export type ResetStewardStateInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountStateAccount extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountStakePool extends string | AccountMeta<string> = string,
  TAccountValidatorList extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountStateAccount extends string
        ? WritableAccount<TAccountStateAccount>
        : TAccountStateAccount,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountStakePool extends string
        ? ReadonlyAccount<TAccountStakePool>
        : TAccountStakePool,
      TAccountValidatorList extends string
        ? ReadonlyAccount<TAccountValidatorList>
        : TAccountValidatorList,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type ResetStewardStateInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type ResetStewardStateInstructionDataArgs = {};

export function getResetStewardStateInstructionDataEncoder(): FixedSizeEncoder<ResetStewardStateInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: RESET_STEWARD_STATE_DISCRIMINATOR })
  );
}

export function getResetStewardStateInstructionDataDecoder(): FixedSizeDecoder<ResetStewardStateInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getResetStewardStateInstructionDataCodec(): FixedSizeCodec<
  ResetStewardStateInstructionDataArgs,
  ResetStewardStateInstructionData
> {
  return combineCodec(
    getResetStewardStateInstructionDataEncoder(),
    getResetStewardStateInstructionDataDecoder()
  );
}

export type ResetStewardStateInput<
  TAccountStateAccount extends string = string,
  TAccountConfig extends string = string,
  TAccountStakePool extends string = string,
  TAccountValidatorList extends string = string,
  TAccountAuthority extends string = string,
> = {
  stateAccount: Address<TAccountStateAccount>;
  config: Address<TAccountConfig>;
  stakePool: Address<TAccountStakePool>;
  validatorList: Address<TAccountValidatorList>;
  authority: TransactionSigner<TAccountAuthority>;
};

export function getResetStewardStateInstruction<
  TAccountStateAccount extends string,
  TAccountConfig extends string,
  TAccountStakePool extends string,
  TAccountValidatorList extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof STEWARD_PROGRAM_ADDRESS,
>(
  input: ResetStewardStateInput<
    TAccountStateAccount,
    TAccountConfig,
    TAccountStakePool,
    TAccountValidatorList,
    TAccountAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): ResetStewardStateInstruction<
  TProgramAddress,
  TAccountStateAccount,
  TAccountConfig,
  TAccountStakePool,
  TAccountValidatorList,
  TAccountAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? STEWARD_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    stateAccount: { value: input.stateAccount ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    stakePool: { value: input.stakePool ?? null, isWritable: false },
    validatorList: { value: input.validatorList ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.stateAccount),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.stakePool),
      getAccountMeta(accounts.validatorList),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getResetStewardStateInstructionDataEncoder().encode({}),
  } as ResetStewardStateInstruction<
    TProgramAddress,
    TAccountStateAccount,
    TAccountConfig,
    TAccountStakePool,
    TAccountValidatorList,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedResetStewardStateInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    stateAccount: TAccountMetas[0];
    config: TAccountMetas[1];
    stakePool: TAccountMetas[2];
    validatorList: TAccountMetas[3];
    authority: TAccountMetas[4];
  };
  data: ResetStewardStateInstructionData;
};

export function parseResetStewardStateInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedResetStewardStateInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      stateAccount: getNextAccount(),
      config: getNextAccount(),
      stakePool: getNextAccount(),
      validatorList: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getResetStewardStateInstructionDataDecoder().decode(instruction.data),
  };
}
