/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { STEWARD_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getUpdatePriorityFeeParametersArgsDecoder,
  getUpdatePriorityFeeParametersArgsEncoder,
  type UpdatePriorityFeeParametersArgs,
  type UpdatePriorityFeeParametersArgsArgs,
} from '../types';

export const UPDATE_PRIORITY_FEE_PARAMETERS_DISCRIMINATOR = new Uint8Array([
  244, 245, 159, 167, 235, 54, 76, 1,
]);

export function getUpdatePriorityFeeParametersDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_PRIORITY_FEE_PARAMETERS_DISCRIMINATOR
  );
}

export type UpdatePriorityFeeParametersInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type UpdatePriorityFeeParametersInstructionData = {
  discriminator: ReadonlyUint8Array;
  updatePriorityFeeParametersArgs: UpdatePriorityFeeParametersArgs;
};

export type UpdatePriorityFeeParametersInstructionDataArgs = {
  updatePriorityFeeParametersArgs: UpdatePriorityFeeParametersArgsArgs;
};

export function getUpdatePriorityFeeParametersInstructionDataEncoder(): Encoder<UpdatePriorityFeeParametersInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      [
        'updatePriorityFeeParametersArgs',
        getUpdatePriorityFeeParametersArgsEncoder(),
      ],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_PRIORITY_FEE_PARAMETERS_DISCRIMINATOR,
    })
  );
}

export function getUpdatePriorityFeeParametersInstructionDataDecoder(): Decoder<UpdatePriorityFeeParametersInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    [
      'updatePriorityFeeParametersArgs',
      getUpdatePriorityFeeParametersArgsDecoder(),
    ],
  ]);
}

export function getUpdatePriorityFeeParametersInstructionDataCodec(): Codec<
  UpdatePriorityFeeParametersInstructionDataArgs,
  UpdatePriorityFeeParametersInstructionData
> {
  return combineCodec(
    getUpdatePriorityFeeParametersInstructionDataEncoder(),
    getUpdatePriorityFeeParametersInstructionDataDecoder()
  );
}

export type UpdatePriorityFeeParametersInput<
  TAccountConfig extends string = string,
  TAccountAuthority extends string = string,
> = {
  config: Address<TAccountConfig>;
  authority: TransactionSigner<TAccountAuthority>;
  updatePriorityFeeParametersArgs: UpdatePriorityFeeParametersInstructionDataArgs['updatePriorityFeeParametersArgs'];
};

export function getUpdatePriorityFeeParametersInstruction<
  TAccountConfig extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof STEWARD_PROGRAM_ADDRESS,
>(
  input: UpdatePriorityFeeParametersInput<TAccountConfig, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress }
): UpdatePriorityFeeParametersInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? STEWARD_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getUpdatePriorityFeeParametersInstructionDataEncoder().encode(
      args as UpdatePriorityFeeParametersInstructionDataArgs
    ),
  } as UpdatePriorityFeeParametersInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedUpdatePriorityFeeParametersInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    authority: TAccountMetas[1];
  };
  data: UpdatePriorityFeeParametersInstructionData;
};

export function parseUpdatePriorityFeeParametersInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUpdatePriorityFeeParametersInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getUpdatePriorityFeeParametersInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
