/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { STEWARD_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getUpdateParametersArgsDecoder,
  getUpdateParametersArgsEncoder,
  type UpdateParametersArgs,
  type UpdateParametersArgsArgs,
} from '../types';

export const UPDATE_PARAMETERS_DISCRIMINATOR = new Uint8Array([
  116, 107, 24, 207, 101, 49, 213, 77,
]);

export function getUpdateParametersDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_PARAMETERS_DISCRIMINATOR
  );
}

export type UpdateParametersInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateParametersInstructionData = {
  discriminator: ReadonlyUint8Array;
  updateParametersArgs: UpdateParametersArgs;
};

export type UpdateParametersInstructionDataArgs = {
  updateParametersArgs: UpdateParametersArgsArgs;
};

export function getUpdateParametersInstructionDataEncoder(): Encoder<UpdateParametersInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['updateParametersArgs', getUpdateParametersArgsEncoder()],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_PARAMETERS_DISCRIMINATOR })
  );
}

export function getUpdateParametersInstructionDataDecoder(): Decoder<UpdateParametersInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['updateParametersArgs', getUpdateParametersArgsDecoder()],
  ]);
}

export function getUpdateParametersInstructionDataCodec(): Codec<
  UpdateParametersInstructionDataArgs,
  UpdateParametersInstructionData
> {
  return combineCodec(
    getUpdateParametersInstructionDataEncoder(),
    getUpdateParametersInstructionDataDecoder()
  );
}

export type UpdateParametersInput<
  TAccountConfig extends string = string,
  TAccountAuthority extends string = string,
> = {
  config: Address<TAccountConfig>;
  authority: TransactionSigner<TAccountAuthority>;
  updateParametersArgs: UpdateParametersInstructionDataArgs['updateParametersArgs'];
};

export function getUpdateParametersInstruction<
  TAccountConfig extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof STEWARD_PROGRAM_ADDRESS,
>(
  input: UpdateParametersInput<TAccountConfig, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress }
): UpdateParametersInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? STEWARD_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getUpdateParametersInstructionDataEncoder().encode(
      args as UpdateParametersInstructionDataArgs
    ),
  } as UpdateParametersInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedUpdateParametersInstruction<
  TProgram extends string = typeof STEWARD_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    authority: TAccountMetas[1];
  };
  data: UpdateParametersInstructionData;
};

export function parseUpdateParametersInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateParametersInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getUpdateParametersInstructionDataDecoder().decode(instruction.data),
  };
}
