use base64::Engine;
use solana_pubkey::Pubkey;
use solana_vote_interface::state::{VoteStateV3, VoteStateV4};
use std::str::FromStr;

fn main() {
    let pubkey = Pubkey::from_str("7tKWFaaLi2FJSqukHxUrnXph8M3ynrqn3kEkKPpgcNHZ").unwrap();

    let base64_data = "AwAAAMpxNQ/hwliQwM4awjHRfyKTYkda1haPiYkHPOrtqMNERRh6Jnd+fAivdJxmI0qazEzj/sVbpmbS7UpoXgKp/49mS6pty+6aVGJZpkQIBfyOD9sgH/tn8q9XyBaPo35wfMpxNQ/hwliQwM4awjHRfyKTYkda1haPiYkHPOrtqMNEAAAQJwAAAAAAAAAAAB8AAAAAAAAAAg6icBgAAAAAHwAAAAIPonAYAAAAAB4AAAABEKJwGAAAAAAdAAAAAhGicBgAAAAAHAAAAAESonAYAAAAABsAAAABE6JwGAAAAAAaAAAAARSicBgAAAAAGQAAAAEVonAYAAAAABgAAAABFqJwGAAAAAAXAAAAAReicBgAAAAAFgAAAAEYonAYAAAAABUAAAACGaJwGAAAAAAUAAAAARqicBgAAAAAEwAAAAIbonAYAAAAABIAAAABHKJwGAAAAAARAAAAAR2icBgAAAAAEAAAAAEeonAYAAAAAA8AAAABH6JwGAAAAAAOAAAAASCicBgAAAAADQAAAAEhonAYAAAAAAwAAAABIqJwGAAAAAALAAAAASOicBgAAAAACgAAAAEkonAYAAAAAAkAAAABJaJwGAAAAAAIAAAAASaicBgAAAAABwAAAAEnonAYAAAAAAYAAAACKKJwGAAAAAAFAAAAASmicBgAAAAABAAAAAEqonAYAAAAAAMAAAABK6JwGAAAAAACAAAAASyicBgAAAAAAQAAAAENonAYAAAAAAIAAAAAAAAAtAMAAAAAAADKcTUP4cJYkMDOGsIx0X8ik2JHWtYWj4mJBzzq7ajDRLUDAAAAAAAAynE1D+HCWJDAzhrCMdF/IpNiR1rWFo+JiQc86u2ow0RAAAAAAAAAAHYDAAAAAAAAhIOFCwAAAADhJhwLAAAAAHcDAAAAAAAARsruCwAAAACEg4ULAAAAAHgDAAAAAAAA6b5XDAAAAABGyu4LAAAAAHkDAAAAAAAAncrADAAAAADpvlcMAAAAAHoDAAAAAAAApvopDQAAAACdysAMAAAAAHsDAAAAAAAAVzyTDQAAAACm+ikNAAAAAHwDAAAAAAAAJIn8DQAAAABXPJMNAAAAAH0DAAAAAAAA+OBlDgAAAAAkifwNAAAAAH4DAAAAAAAABzrPDgAAAAD44GUOAAAAAH8DAAAAAAAAR5A4DwAAAAAHOs8OAAAAAIADAAAAAAAABOahDwAAAABHkDgPAAAAAIEDAAAAAAAAVkULEAAAAAAE5qEPAAAAAIIDAAAAAAAA3pl0EAAAAABWRQsQAAAAAIMDAAAAAAAAvu3dEAAAAADemXQQAAAAAIQDAAAAAAAAYVhHEQAAAAC+7d0QAAAAAIUDAAAAAAAAY5uwEQAAAABhWEcRAAAAAIYDAAAAAAAA/pQZEgAAAABjm7ARAAAAAIcDAAAAAAAAFPyCEgAAAAD+lBkSAAAAAIgDAAAAAAAAIFTsEgAAAAAU/IISAAAAAIkDAAAAAAAAdo9VEwAAAAAgVOwSAAAAAIoDAAAAAAAAKdW+EwAAAAB2j1UTAAAAAIsDAAAAAAAAougnFAAAAAAp1b4TAAAAAIwDAAAAAAAARniQFAAAAACi6CcUAAAAAI0DAAAAAAAA5A/4FAAAAABGeJAUAAAAAI4DAAAAAAAAkAZhFQAAAADkD/gUAAAAAI8DAAAAAAAA1kHKFQAAAACQBmEVAAAAAJADAAAAAAAA2Y4zFgAAAADWQcoVAAAAAJEDAAAAAAAAnsacFgAAAADZjjMWAAAAAJIDAAAAAAAAW+oFFwAAAACexpwWAAAAAJMDAAAAAAAAsPluFwAAAABb6gUXAAAAAJQDAAAAAAAAHszXFwAAAACw+W4XAAAAAJUDAAAAAAAAQYBAGAAAAAAezNcXAAAAAJYDAAAAAAAAOlapGAAAAABBgEAYAAAAAJcDAAAAAAAA9msSGQAAAAA6VqkYAAAAAJgDAAAAAAAALJ97GQAAAAD2axIZAAAAAJkDAAAAAAAA16TjGQAAAAAsn3sZAAAAAJoDAAAAAAAAJ9pMGgAAAADXpOMZAAAAAJsDAAAAAAAAu/S1GgAAAAAn2kwaAAAAAJwDAAAAAAAA9S0fGwAAAAC79LUaAAAAAJ0DAAAAAAAAj4OIGwAAAAD1LR8bAAAAAJ4DAAAAAAAAT8/xGwAAAACPg4gbAAAAAJ8DAAAAAAAAYvhaHAAAAABPz/EbAAAAAKADAAAAAAAAFSHEHAAAAABi+FocAAAAAKEDAAAAAAAA6WotHQAAAAAVIcQcAAAAAKIDAAAAAAAAHnWWHQAAAADpai0dAAAAAKMDAAAAAAAAbaP/HQAAAAAedZYdAAAAAKQDAAAAAAAAS+NoHgAAAABto/8dAAAAAKUDAAAAAAAA+OTRHgAAAABL42geAAAAAKYDAAAAAAAAteg6HwAAAAD45NEeAAAAAKcDAAAAAAAAGyqkHwAAAAC16DofAAAAAKgDAAAAAAAAKl8NIAAAAAAbKqQfAAAAAKkDAAAAAAAAH6x2IAAAAAAqXw0gAAAAAKoDAAAAAAAA99zfIAAAAAAfrHYgAAAAAKsDAAAAAAAAeCJJIQAAAAD33N8gAAAAAKwDAAAAAAAAKYOyIQAAAAB4IkkhAAAAAK0DAAAAAAAAJ+YbIgAAAAApg7IhAAAAAK4DAAAAAAAAoCaFIgAAAAAn5hsiAAAAAK8DAAAAAAAAYmDuIgAAAACgJoUiAAAAALADAAAAAAAA1blXIwAAAABiYO4iAAAAALEDAAAAAAAA1QPBIwAAAADVuVcjAAAAALIDAAAAAAAAPDkqJAAAAADVA8EjAAAAALMDAAAAAAAA+YKTJAAAAAA8OSokAAAAALQDAAAAAAAAi9P8JAAAAAD5gpMkAAAAACyicBgAAAAAWmnLaQAAAAAAAAAAAKb6KQ0AAAAAncrADAAAAAB7AwAAAAAAAFc8kw0AAAAApvopDQAAAAB8AwAAAAAAACSJ/A0AAAAAVzyTDQAAAAB9AwAAAAAAAPjgZQ4AAAAAJIn8DQAAAAB+AwAAAAAAAAc6zw4AAAAA+OBlDgAAAAB/AwAAAAAAAEeQOA8AAAAABzrPDgAAAACAAwAAAAAAAATmoQ8AAAAAR5A4DwAAAACBAwAAAAAAAFZFCxAAAAAABOahDwAAAACCAwAAAAAAAN6ZdBAAAAAAVkULEAAAAACDAwAAAAAAAL7t3RAAAAAA3pl0EAAAAACEAwAAAAAAAGFYRxEAAAAAvu3dEAAAAACFAwAAAAAAAGObsBEAAAAAYVhHEQAAAACGAwAAAAAAAP6UGRIAAAAAY5uwEQAAAACHAwAAAAAAABT8ghIAAAAA/pQZEgAAAACIAwAAAAAAACBU7BIAAAAAFPyCEgAAAACJAwAAAAAAAHaPVRMAAAAAIFTsEgAAAACKAwAAAAAAACnVvhMAAAAAdo9VEwAAAACLAwAAAAAAAKLoJxQAAAAAKdW+EwAAAACMAwAAAAAAAEZ4kBQAAAAAougnFAAAAACNAwAAAAAAAOQP+BQAAAAARniQFAAAAACOAwAAAAAAAJAGYRUAAAAA5A/4FAAAAACPAwAAAAAAANZByhUAAAAAkAZhFQAAAACQAwAAAAAAANmOMxYAAAAA1kHKFQAAAACRAwAAAAAAAJ7GnBYAAAAA2Y4zFgAAAACSAwAAAAAAAFvqBRcAAAAAnsacFgAAAACTAwAAAAAAALD5bhcAAAAAW+oFFwAAAACUAwAAAAAAAB7M1xcAAAAAsPluFwAAAACVAwAAAAAAAEGAQBgAAAAAHszXFwAAAACWAwAAAAAAADpWqRgAAAAAQYBAGAAAAACXAwAAAAAAAPZrEhkAAAAAOlapGAAAAACYAwAAAAAAACyfexkAAAAA9msSGQAAAACZAwAAAAAAANek4xkAAAAALJ97GQAAAACaAwAAAAAAACfaTBoAAAAA16TjGQAAAACbAwAAAAAAALv0tRoAAAAAJ9pMGgAAAACcAwAAAAAAAPUtHxsAAAAAu/S1GgAAAACdAwAAAAAAAI+DiBsAAAAA9S0fGwAAAACeAwAAAAAAAE/P8RsAAAAAj4OIGwAAAACfAwAAAAAAAGL4WhwAAAAAT8/xGwAAAACgAwAAAAAAABUhxBwAAAAAYvhaHAAAAAChAwAAAAAAAOlqLR0AAAAAFSHEHAAAAACiAwAAAAAAAB51lh0AAAAA6WotHQAAAACjAwAAAAAAAG2j/x0AAAAAHnWWHQAAAACkAwAAAAAAAEvjaB4AAAAAbaP/HQAAAAClAwAAAAAAAPjk0R4AAAAAS+NoHgAAAACmAwAAAAAAALXoOh8AAAAA+OTRHgAAAACnAwAAAAAAABsqpB8AAAAAteg6HwAAAACoAwAAAAAAACpfDSAAAAAAGyqkHwAAAACpAwAAAAAAAB+sdiAAAAAAKl8NIAAAAACqAwAAAAAAAPfc3yAAAAAAH6x2IAAAAACrAwAAAAAAAHgiSSEAAAAA99zfIAAAAACsAwAAAAAAACmDsiEAAAAAeCJJIQAAAACtAwAAAAAAACfmGyIAAAAAKYOyIQAAAACuAwAAAAAAAKAmhSIAAAAAJ+YbIgAAAACvAwAAAAAAAGJg7iIAAAAAoCaFIgAAAACwAwAAAAAAANW5VyMAAAAAYmDuIgAAAACxAwAAAAAAANUDwSMAAAAA1blXIwAAAACyAwAAAAAAADw5KiQAAAAA1QPBIwAAAACzAwAAAAAAAPmCkyQAAAAAPDkqJAAAAAC0AwAAAAAAAIvT/CQAAAAA+YKTJAAAAAB+nW8YAAAAAEQDy2kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    let raw_data = base64::engine::general_purpose::STANDARD
        .decode(base64_data)
        .unwrap();

    println!("Data length: {} bytes", raw_data.len());
    println!(
        "Version discriminant: {}",
        u32::from_le_bytes(raw_data[0..4].try_into().unwrap())
    );
    println!();

    // Attempt 1: VoteStateV3::deserialize (only handles discriminants 0, 1, 2)
    match VoteStateV3::deserialize(&raw_data) {
        Ok(v3) => {
            println!("VoteStateV3::deserialize succeeded!");
            println!("  node_pubkey: {}", v3.node_pubkey);
            println!("  commission: {}", v3.commission);
            println!("  epoch_credits count: {}", v3.epoch_credits.len());
            if let Some(last) = v3.epoch_credits.last() {
                println!("  latest epoch: {}", last.0);
            }
        }
        Err(e) => {
            println!("VoteStateV3::deserialize FAILED: {:?}", e);
        }
    }

    println!();

    // Attempt 2: VoteStateV4::deserialize (handles discriminants 0, 1, 2, 3)
    match VoteStateV4::deserialize(&raw_data, &pubkey) {
        Ok(v4) => {
            println!("VoteStateV4::deserialize succeeded!");
            println!("  node_pubkey: {}", v4.node_pubkey);
            println!(
                "  inflation_rewards_commission_bps: {}",
                v4.inflation_rewards_commission_bps
            );
            println!(
                "  block_revenue_commission_bps: {}",
                v4.block_revenue_commission_bps
            );
            println!("  bls_pubkey_compressed: {:?}", v4.bls_pubkey_compressed);
            println!("  epoch_credits count: {}", v4.epoch_credits.len());
            if let Some(last) = v4.epoch_credits.last() {
                println!("  latest epoch: {}", last.0);
            }
        }
        Err(e) => {
            println!("VoteStateV4::deserialize FAILED: {:?}", e);
        }
    }
}
