/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { STEWARD_PROGRAM_ADDRESS } from '../programs';

/** InvalidAuthorityType: Invalid set authority type: 0: SetAdmin, 1: SetBlacklistAuthority, 2: SetParametersAuthority */
export const STEWARD_ERROR__INVALID_AUTHORITY_TYPE = 0x1770; // 6000
/** ScoringNotComplete: Scoring must be completed before any other steps can be taken */
export const STEWARD_ERROR__SCORING_NOT_COMPLETE = 0x1771; // 6001
/** ValidatorNotInList: Validator does not exist at the ValidatorList index provided */
export const STEWARD_ERROR__VALIDATOR_NOT_IN_LIST = 0x1772; // 6002
/** Unauthorized: Unauthorized to perform this action */
export const STEWARD_ERROR__UNAUTHORIZED = 0x1773; // 6003
/** BitmaskOutOfBounds: Bitmask index out of bounds */
export const STEWARD_ERROR__BITMASK_OUT_OF_BOUNDS = 0x1774; // 6004
/** InvalidState: Invalid state */
export const STEWARD_ERROR__INVALID_STATE = 0x1775; // 6005
/** StakeStateIsNotStake: Stake state is not Stake */
export const STEWARD_ERROR__STAKE_STATE_IS_NOT_STAKE = 0x1776; // 6006
/** ValidatorBelowStakeMinimum: Validator not eligible to be added to the pool. Must meet stake minimum */
export const STEWARD_ERROR__VALIDATOR_BELOW_STAKE_MINIMUM = 0x1777; // 6007
/** ValidatorBelowLivenessMinimum: Validator not eligible to be added to the pool. Must meet recent voting minimum */
export const STEWARD_ERROR__VALIDATOR_BELOW_LIVENESS_MINIMUM = 0x1778; // 6008
/** VoteHistoryNotRecentEnough: Validator History vote data not recent enough to be used for scoring. Must be updated this epoch */
export const STEWARD_ERROR__VOTE_HISTORY_NOT_RECENT_ENOUGH = 0x1779; // 6009
/** StakeHistoryNotRecentEnough: Validator History stake data not recent enough to be used for scoring. Must be updated this epoch */
export const STEWARD_ERROR__STAKE_HISTORY_NOT_RECENT_ENOUGH = 0x177a; // 6010
/** ClusterHistoryNotRecentEnough: Cluster History data not recent enough to be used for scoring. Must be updated this epoch */
export const STEWARD_ERROR__CLUSTER_HISTORY_NOT_RECENT_ENOUGH = 0x177b; // 6011
/** StateMachinePaused: Steward State Machine is paused. No state machine actions can be taken */
export const STEWARD_ERROR__STATE_MACHINE_PAUSED = 0x177c; // 6012
/** InvalidParameterValue: Config parameter is out of range or otherwise invalid */
export const STEWARD_ERROR__INVALID_PARAMETER_VALUE = 0x177d; // 6013
/** InstantUnstakeNotReady: Instant unstake cannot be performed yet. */
export const STEWARD_ERROR__INSTANT_UNSTAKE_NOT_READY = 0x177e; // 6014
/** ValidatorIndexOutOfBounds: Validator index out of bounds of state machine */
export const STEWARD_ERROR__VALIDATOR_INDEX_OUT_OF_BOUNDS = 0x177f; // 6015
/** ValidatorListTypeMismatch: ValidatorList account type mismatch */
export const STEWARD_ERROR__VALIDATOR_LIST_TYPE_MISMATCH = 0x1780; // 6016
/** ArithmeticError: An operation caused an overflow/underflow */
export const STEWARD_ERROR__ARITHMETIC_ERROR = 0x1781; // 6017
/** ValidatorNotRemovable: Validator not eligible for removal. Must be delinquent or have closed vote account */
export const STEWARD_ERROR__VALIDATOR_NOT_REMOVABLE = 0x1782; // 6018
/** ValidatorMarkedActive: Validator was marked active when it should be deactivating */
export const STEWARD_ERROR__VALIDATOR_MARKED_ACTIVE = 0x1783; // 6019
/** MaxValidatorsReached: Max validators reached */
export const STEWARD_ERROR__MAX_VALIDATORS_REACHED = 0x1784; // 6020
/** EpochMaintenanceNotComplete: Epoch Maintenance must be called before continuing */
export const STEWARD_ERROR__EPOCH_MAINTENANCE_NOT_COMPLETE = 0x1785; // 6021
/** StakePoolNotUpdated: The stake pool must be updated before continuing */
export const STEWARD_ERROR__STAKE_POOL_NOT_UPDATED = 0x1786; // 6022
/** EpochMaintenanceAlreadyComplete: Epoch Maintenance has already been completed */
export const STEWARD_ERROR__EPOCH_MAINTENANCE_ALREADY_COMPLETE = 0x1787; // 6023
/** ValidatorsNeedToBeRemoved: Validators are marked for immediate removal */
export const STEWARD_ERROR__VALIDATORS_NEED_TO_BE_REMOVED = 0x1788; // 6024
/** ValidatorNotMarkedForRemoval: Validator not marked for removal */
export const STEWARD_ERROR__VALIDATOR_NOT_MARKED_FOR_REMOVAL = 0x1789; // 6025
/** ValidatorsHaveNotBeenRemoved: Validators have not been removed */
export const STEWARD_ERROR__VALIDATORS_HAVE_NOT_BEEN_REMOVED = 0x178a; // 6026
/** ListStateMismatch: Validator List count does not match state machine */
export const STEWARD_ERROR__LIST_STATE_MISMATCH = 0x178b; // 6027
/** VoteAccountDoesNotMatch: Vote account does not match */
export const STEWARD_ERROR__VOTE_ACCOUNT_DOES_NOT_MATCH = 0x178c; // 6028
/** ValidatorNeedsToBeMarkedForRemoval: Validator needs to be marked for removal */
export const STEWARD_ERROR__VALIDATOR_NEEDS_TO_BE_MARKED_FOR_REMOVAL = 0x178d; // 6029
/** InvalidStakeState: Invalid stake state */
export const STEWARD_ERROR__INVALID_STAKE_STATE = 0x178e; // 6030
/** ArithmeticCastError: Arithmetic casting error */
export const STEWARD_ERROR__ARITHMETIC_CAST_ERROR = 0x178f; // 6031

export type StewardError =
  | typeof STEWARD_ERROR__ARITHMETIC_CAST_ERROR
  | typeof STEWARD_ERROR__ARITHMETIC_ERROR
  | typeof STEWARD_ERROR__BITMASK_OUT_OF_BOUNDS
  | typeof STEWARD_ERROR__CLUSTER_HISTORY_NOT_RECENT_ENOUGH
  | typeof STEWARD_ERROR__EPOCH_MAINTENANCE_ALREADY_COMPLETE
  | typeof STEWARD_ERROR__EPOCH_MAINTENANCE_NOT_COMPLETE
  | typeof STEWARD_ERROR__INSTANT_UNSTAKE_NOT_READY
  | typeof STEWARD_ERROR__INVALID_AUTHORITY_TYPE
  | typeof STEWARD_ERROR__INVALID_PARAMETER_VALUE
  | typeof STEWARD_ERROR__INVALID_STAKE_STATE
  | typeof STEWARD_ERROR__INVALID_STATE
  | typeof STEWARD_ERROR__LIST_STATE_MISMATCH
  | typeof STEWARD_ERROR__MAX_VALIDATORS_REACHED
  | typeof STEWARD_ERROR__SCORING_NOT_COMPLETE
  | typeof STEWARD_ERROR__STAKE_HISTORY_NOT_RECENT_ENOUGH
  | typeof STEWARD_ERROR__STAKE_POOL_NOT_UPDATED
  | typeof STEWARD_ERROR__STAKE_STATE_IS_NOT_STAKE
  | typeof STEWARD_ERROR__STATE_MACHINE_PAUSED
  | typeof STEWARD_ERROR__UNAUTHORIZED
  | typeof STEWARD_ERROR__VALIDATOR_BELOW_LIVENESS_MINIMUM
  | typeof STEWARD_ERROR__VALIDATOR_BELOW_STAKE_MINIMUM
  | typeof STEWARD_ERROR__VALIDATOR_INDEX_OUT_OF_BOUNDS
  | typeof STEWARD_ERROR__VALIDATOR_LIST_TYPE_MISMATCH
  | typeof STEWARD_ERROR__VALIDATOR_MARKED_ACTIVE
  | typeof STEWARD_ERROR__VALIDATOR_NEEDS_TO_BE_MARKED_FOR_REMOVAL
  | typeof STEWARD_ERROR__VALIDATOR_NOT_IN_LIST
  | typeof STEWARD_ERROR__VALIDATOR_NOT_MARKED_FOR_REMOVAL
  | typeof STEWARD_ERROR__VALIDATOR_NOT_REMOVABLE
  | typeof STEWARD_ERROR__VALIDATORS_HAVE_NOT_BEEN_REMOVED
  | typeof STEWARD_ERROR__VALIDATORS_NEED_TO_BE_REMOVED
  | typeof STEWARD_ERROR__VOTE_ACCOUNT_DOES_NOT_MATCH
  | typeof STEWARD_ERROR__VOTE_HISTORY_NOT_RECENT_ENOUGH;

let stewardErrorMessages: Record<StewardError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  stewardErrorMessages = {
    [STEWARD_ERROR__ARITHMETIC_CAST_ERROR]: `Arithmetic casting error`,
    [STEWARD_ERROR__ARITHMETIC_ERROR]: `An operation caused an overflow/underflow`,
    [STEWARD_ERROR__BITMASK_OUT_OF_BOUNDS]: `Bitmask index out of bounds`,
    [STEWARD_ERROR__CLUSTER_HISTORY_NOT_RECENT_ENOUGH]: `Cluster History data not recent enough to be used for scoring. Must be updated this epoch`,
    [STEWARD_ERROR__EPOCH_MAINTENANCE_ALREADY_COMPLETE]: `Epoch Maintenance has already been completed`,
    [STEWARD_ERROR__EPOCH_MAINTENANCE_NOT_COMPLETE]: `Epoch Maintenance must be called before continuing`,
    [STEWARD_ERROR__INSTANT_UNSTAKE_NOT_READY]: `Instant unstake cannot be performed yet.`,
    [STEWARD_ERROR__INVALID_AUTHORITY_TYPE]: `Invalid set authority type: 0: SetAdmin, 1: SetBlacklistAuthority, 2: SetParametersAuthority`,
    [STEWARD_ERROR__INVALID_PARAMETER_VALUE]: `Config parameter is out of range or otherwise invalid`,
    [STEWARD_ERROR__INVALID_STAKE_STATE]: `Invalid stake state`,
    [STEWARD_ERROR__INVALID_STATE]: `Invalid state`,
    [STEWARD_ERROR__LIST_STATE_MISMATCH]: `Validator List count does not match state machine`,
    [STEWARD_ERROR__MAX_VALIDATORS_REACHED]: `Max validators reached`,
    [STEWARD_ERROR__SCORING_NOT_COMPLETE]: `Scoring must be completed before any other steps can be taken`,
    [STEWARD_ERROR__STAKE_HISTORY_NOT_RECENT_ENOUGH]: `Validator History stake data not recent enough to be used for scoring. Must be updated this epoch`,
    [STEWARD_ERROR__STAKE_POOL_NOT_UPDATED]: `The stake pool must be updated before continuing`,
    [STEWARD_ERROR__STAKE_STATE_IS_NOT_STAKE]: `Stake state is not Stake`,
    [STEWARD_ERROR__STATE_MACHINE_PAUSED]: `Steward State Machine is paused. No state machine actions can be taken`,
    [STEWARD_ERROR__UNAUTHORIZED]: `Unauthorized to perform this action`,
    [STEWARD_ERROR__VALIDATOR_BELOW_LIVENESS_MINIMUM]: `Validator not eligible to be added to the pool. Must meet recent voting minimum`,
    [STEWARD_ERROR__VALIDATOR_BELOW_STAKE_MINIMUM]: `Validator not eligible to be added to the pool. Must meet stake minimum`,
    [STEWARD_ERROR__VALIDATOR_INDEX_OUT_OF_BOUNDS]: `Validator index out of bounds of state machine`,
    [STEWARD_ERROR__VALIDATOR_LIST_TYPE_MISMATCH]: `ValidatorList account type mismatch`,
    [STEWARD_ERROR__VALIDATOR_MARKED_ACTIVE]: `Validator was marked active when it should be deactivating`,
    [STEWARD_ERROR__VALIDATOR_NEEDS_TO_BE_MARKED_FOR_REMOVAL]: `Validator needs to be marked for removal`,
    [STEWARD_ERROR__VALIDATOR_NOT_IN_LIST]: `Validator does not exist at the ValidatorList index provided`,
    [STEWARD_ERROR__VALIDATOR_NOT_MARKED_FOR_REMOVAL]: `Validator not marked for removal`,
    [STEWARD_ERROR__VALIDATOR_NOT_REMOVABLE]: `Validator not eligible for removal. Must be delinquent or have closed vote account`,
    [STEWARD_ERROR__VALIDATORS_HAVE_NOT_BEEN_REMOVED]: `Validators have not been removed`,
    [STEWARD_ERROR__VALIDATORS_NEED_TO_BE_REMOVED]: `Validators are marked for immediate removal`,
    [STEWARD_ERROR__VOTE_ACCOUNT_DOES_NOT_MATCH]: `Vote account does not match`,
    [STEWARD_ERROR__VOTE_HISTORY_NOT_RECENT_ENOUGH]: `Validator History vote data not recent enough to be used for scoring. Must be updated this epoch`,
  };
}

export function getStewardErrorMessage(code: StewardError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (stewardErrorMessages as Record<StewardError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isStewardError<TProgramErrorCode extends StewardError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    STEWARD_PROGRAM_ADDRESS,
    code
  );
}
