/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type AutoAddValidatorEvent = {
  validatorListIndex: bigint;
  voteAccount: Address;
};

export type AutoAddValidatorEventArgs = {
  validatorListIndex: number | bigint;
  voteAccount: Address;
};

export function getAutoAddValidatorEventEncoder(): FixedSizeEncoder<AutoAddValidatorEventArgs> {
  return getStructEncoder([
    ['validatorListIndex', getU64Encoder()],
    ['voteAccount', getAddressEncoder()],
  ]);
}

export function getAutoAddValidatorEventDecoder(): FixedSizeDecoder<AutoAddValidatorEvent> {
  return getStructDecoder([
    ['validatorListIndex', getU64Decoder()],
    ['voteAccount', getAddressDecoder()],
  ]);
}

export function getAutoAddValidatorEventCodec(): FixedSizeCodec<
  AutoAddValidatorEventArgs,
  AutoAddValidatorEvent
> {
  return combineCodec(
    getAutoAddValidatorEventEncoder(),
    getAutoAddValidatorEventDecoder()
  );
}
