/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type AutoRemoveValidatorEvent = {
  validatorListIndex: bigint;
  voteAccount: Address;
  voteAccountClosed: boolean;
  stakeAccountDeactivated: boolean;
  markedForImmediateRemoval: boolean;
};

export type AutoRemoveValidatorEventArgs = {
  validatorListIndex: number | bigint;
  voteAccount: Address;
  voteAccountClosed: boolean;
  stakeAccountDeactivated: boolean;
  markedForImmediateRemoval: boolean;
};

export function getAutoRemoveValidatorEventEncoder(): FixedSizeEncoder<AutoRemoveValidatorEventArgs> {
  return getStructEncoder([
    ['validatorListIndex', getU64Encoder()],
    ['voteAccount', getAddressEncoder()],
    ['voteAccountClosed', getBooleanEncoder()],
    ['stakeAccountDeactivated', getBooleanEncoder()],
    ['markedForImmediateRemoval', getBooleanEncoder()],
  ]);
}

export function getAutoRemoveValidatorEventDecoder(): FixedSizeDecoder<AutoRemoveValidatorEvent> {
  return getStructDecoder([
    ['validatorListIndex', getU64Decoder()],
    ['voteAccount', getAddressDecoder()],
    ['voteAccountClosed', getBooleanDecoder()],
    ['stakeAccountDeactivated', getBooleanDecoder()],
    ['markedForImmediateRemoval', getBooleanDecoder()],
  ]);
}

export function getAutoRemoveValidatorEventCodec(): FixedSizeCodec<
  AutoRemoveValidatorEventArgs,
  AutoRemoveValidatorEvent
> {
  return combineCodec(
    getAutoRemoveValidatorEventEncoder(),
    getAutoRemoveValidatorEventDecoder()
  );
}
