/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum RebalanceTypeTag {
  None,
  Increase,
  Decrease,
}

export type RebalanceTypeTagArgs = RebalanceTypeTag;

export function getRebalanceTypeTagEncoder(): FixedSizeEncoder<RebalanceTypeTagArgs> {
  return getEnumEncoder(RebalanceTypeTag);
}

export function getRebalanceTypeTagDecoder(): FixedSizeDecoder<RebalanceTypeTag> {
  return getEnumDecoder(RebalanceTypeTag);
}

export function getRebalanceTypeTagCodec(): FixedSizeCodec<
  RebalanceTypeTagArgs,
  RebalanceTypeTag
> {
  return combineCodec(
    getRebalanceTypeTagEncoder(),
    getRebalanceTypeTagDecoder()
  );
}
