/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getF64Decoder,
  getF64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/**
 * Deprecated: This struct is no longer emitted but is kept to allow parsing of old events.
 * Because the event discriminator is based on struct name, it's important to rename the struct if
 * fields are changed.
 */

export type ScoreComponents = {
  score: number;
  yieldScore: number;
  mevCommissionScore: number;
  blacklistedScore: number;
  superminorityScore: number;
  delinquencyScore: number;
  runningJitoScore: number;
  commissionScore: number;
  historicalCommissionScore: number;
  voteCreditsRatio: number;
  voteAccount: Address;
  epoch: number;
};

export type ScoreComponentsArgs = ScoreComponents;

export function getScoreComponentsEncoder(): FixedSizeEncoder<ScoreComponentsArgs> {
  return getStructEncoder([
    ['score', getF64Encoder()],
    ['yieldScore', getF64Encoder()],
    ['mevCommissionScore', getF64Encoder()],
    ['blacklistedScore', getF64Encoder()],
    ['superminorityScore', getF64Encoder()],
    ['delinquencyScore', getF64Encoder()],
    ['runningJitoScore', getF64Encoder()],
    ['commissionScore', getF64Encoder()],
    ['historicalCommissionScore', getF64Encoder()],
    ['voteCreditsRatio', getF64Encoder()],
    ['voteAccount', getAddressEncoder()],
    ['epoch', getU16Encoder()],
  ]);
}

export function getScoreComponentsDecoder(): FixedSizeDecoder<ScoreComponents> {
  return getStructDecoder([
    ['score', getF64Decoder()],
    ['yieldScore', getF64Decoder()],
    ['mevCommissionScore', getF64Decoder()],
    ['blacklistedScore', getF64Decoder()],
    ['superminorityScore', getF64Decoder()],
    ['delinquencyScore', getF64Decoder()],
    ['runningJitoScore', getF64Decoder()],
    ['commissionScore', getF64Decoder()],
    ['historicalCommissionScore', getF64Decoder()],
    ['voteCreditsRatio', getF64Decoder()],
    ['voteAccount', getAddressDecoder()],
    ['epoch', getU16Decoder()],
  ]);
}

export function getScoreComponentsCodec(): FixedSizeCodec<
  ScoreComponentsArgs,
  ScoreComponents
> {
  return combineCodec(getScoreComponentsEncoder(), getScoreComponentsDecoder());
}
