/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum StewardStateEnum {
  ComputeScores,
  ComputeDelegations,
  Idle,
  ComputeInstantUnstake,
  Rebalance,
}

export type StewardStateEnumArgs = StewardStateEnum;

export function getStewardStateEnumEncoder(): FixedSizeEncoder<StewardStateEnumArgs> {
  return getEnumEncoder(StewardStateEnum);
}

export function getStewardStateEnumDecoder(): FixedSizeDecoder<StewardStateEnum> {
  return getEnumDecoder(StewardStateEnum);
}

export function getStewardStateEnumCodec(): FixedSizeCodec<
  StewardStateEnumArgs,
  StewardStateEnum
> {
  return combineCodec(
    getStewardStateEnumEncoder(),
    getStewardStateEnumDecoder()
  );
}
