/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/** A boolean type stored as a u8. */
export type U8Bool = { value: number };

export type U8BoolArgs = U8Bool;

export function getU8BoolEncoder(): FixedSizeEncoder<U8BoolArgs> {
  return getStructEncoder([['value', getU8Encoder()]]);
}

export function getU8BoolDecoder(): FixedSizeDecoder<U8Bool> {
  return getStructDecoder([['value', getU8Decoder()]]);
}

export function getU8BoolCodec(): FixedSizeCodec<U8BoolArgs, U8Bool> {
  return combineCodec(getU8BoolEncoder(), getU8BoolDecoder());
}
